tools:
  threads: 10
  rate_limit: 150
  timeout: 30

api_keys:
  securitytrails: ""
  shodan: ""
  censys: ""
  virustotal: ""
  wpscan: ""

wordlists:
  dns: /usr/share/wordlists/dns.txt
  content: /usr/share/wordlists/dirb/common.txt

output:
  format: json
  directory: output 