api_keys:
  chaos: ''
  github: ''
  securitytrails: 'h__MNTv6tIfmuWRvow0Zdo9_miXmckDC'
  wayback: ''
output:
  directory: output
  formats:
  - json
  - markdown
  - html
tools:
  max_retries: 3
  threads: 10
  timeout: 300
